[package]
name = "ashina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures03 = { package = "futures", version = "0.3", features = ["compat"] }
log = "0.4"
